//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number_Phone
    {
        public int Number_Zapisi { get; set; }
        public Nullable<decimal> Number_Phone1 { get; set; }
        public Nullable<int> Number_User { get; set; }
        public Nullable<int> Number_Type { get; set; }
        public string Picture { get; set; }
    
        public virtual Number_Users Number_Users { get; set; }
        public virtual Type_Phone Type_Phone { get; set; }
    }
}
