//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KPGalishnikovEntities : DbContext
    {
        private static KPGalishnikovEntities _context;
        public KPGalishnikovEntities()
            : base("name=KPGalishnikovEntities")
        {
        }
        public static KPGalishnikovEntities GetContext()
        {
            if (_context == null)
                _context = new KPGalishnikovEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Number_Phone> Number_Phone { get; set; }
        public virtual DbSet<Number_Users> Number_Users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Phone> Type_Phone { get; set; }
    }
}
